### ISSUE TITLE
gulp-cheerio fails due to issue with cheerio

### ISSUE THREAD

**Issue by nevin** [knpwrs/gulp-cheerio#13]
Due to the update in cheerio version from 0.20.0 to 0.21.0 - this plugin is failing

**Comment by knpwrs** [comment]
It seems like `0.20.0` is the latest version published? The following works fine for me:

```
glcd git@github.com:knpwrs/gulp-cheerio.git
npm i
npm test
```

**Comment by nevin** [comment]
It was not. There was a release 0.21.0 and they reverted it after a day due to the issue.

**Comment by nevin** [comment]
I raised the request when before reverting and u checked it after reverting so its working for u

**Comment by TomMalufe** [comment]
This issue has been driving me crazy for the past 24 hours.  I'm glad I'm not the only one who was experiencing it.  Reverting back to cheerio@0.20.0 worked for me.

**Comment by knpwrs** [comment]
Is this currently an issue? `0.20.0` is still the most recent published version on npm.

**Comment by TomMalufe** [comment]
However, the version in [package.json](https://github.com/cheeriojs/cheerio/blob/master/package.json) is still 0.21.0 and so npm is still grabbing that version when I install.  I had to delete cheerio from my `node_modules` and run `npm install cheerio@0.20.0` to solve my issue.

**Comment by knpwrs** [comment]
The version on NPM is still `0.20.0`:

![image](https://cloud.githubusercontent.com/assets/174864/16181434/de22bdaa-3669-11e6-90d1-27eaf4917b29.png)

You have to manually publish new versions to NPM. NPM will only install from Github if you tell it to.

**Comment by TomMalufe** [comment]
All I know is that if I run `npm install gulp-cheerio` in a clean directory 
then run `npm list | grep cheerio` 
it prints 
`└─┬ gulp-cheerio@0.6.2`
  `├─┬ cheerio@0.21.0`

However, I do have my npm registry set to our company's private registry.  Do you think that could be causing me to grab the wrong version?

**Comment by caillou** [comment]
@nevin do you still experience the problem with 0.22.0? Else I would recommend to close the issue.

**Comment by nevin** [comment]
Please close the issue
