### ISSUE TITLE
Content is escaped when passed through gulp cheerio

### ISSUE THREAD

**Issue by oleersoy** [knpwrs/gulp-cheerio#17]
I have a Gulp Task that I used to generate CSS unit tests.  It's located here and uses `gulp-cheerio` to copy some content before it's highlighted:

https://github.com/superfly-css/superfly-css-task-test/blob/master/src/main/js/index.js

The test can be run by cloning the repository and running `rm -fr target/ && gulp test:css && cat target/test/html/index.html `.

If I comment out the `gulp-cheerio` section of the task, the nunjucks template portion of the test renders fine:

``` html
   {% for item in ['100', '300'] %}
      <div class="u-color-background-gray-{{item}}>
        <code>u-color-background-gray-{{item}}</code>
      </div>
   {% endfor %}
```

However if the above rendered content is passed through the `gulp-cheerio` section of the task it's partially escaped like this:
``` html
      <div class="u-color-background-gray-100&gt;
        &lt;code&gt;u-color-background-gray-100&lt;/code&gt;
      &lt;/div&gt;
   
      &lt;div class=" u-color-background-gray-300="">
        <code>u-color-background-gray-300</code>
      </div>
```

.  Any idea why this is?

**Comment by oleersoy** [comment]
Added a little more background here:
http://stackoverflow.com/questions/41819997/gulp-cheerio-is-partially-escaping-html-elements

**Comment by oleersoy** [comment]
I did some more experimenting.  I wanted to see whether `gulp-cheerio` would escape the same content when it's static, so I commented out the template and just pasted in the rendered result.  It does not escape the static content, and the interesting part is that it correctly renders the template when it is inside the html comments.  So the below snippet:

``` html
<!--
   {% for item in ['100', '300'] %}
      <div class="u-color-background-gray-{{item}}>
        <code>u-color-background-gray-{{item}}</code>
      </div>
   {% endfor %}
-->

  <div class="u-color-background-gray-100">
  </div>

  <div class="u-color-background-gray-100">
  </div>
```

Renders like this:
``` html
<!--
   
      <div class="u-color-background-gray-100>
        <code>u-color-background-gray-100</code>
      </div>
   
      <div class="u-color-background-gray-300>
        <code>u-color-background-gray-300</code>
      </div>
   
-->

  <div class="u-color-background-gray-100">
  </div>

  <div class="u-color-background-gray-100">
  </div>
```

**Comment by oleersoy** [comment]
Created a separate minimal example repository illustrating what is happening here:
https://github.com/oleersoy/nunjucks-cheerio/

**Comment by knpwrs** [comment]
Sorry, just saw this. It appears that you are missing a `"` from your html. This:

```
<div class="u-color-background-gray-{{item}}>
```

Should be;

```
<div class="u-color-background-gray-{{item}}">
```

That change gets your repo to work for me.

**Comment by oleersoy** [comment]
DOH!!  Thanks for the heads up!  Thanks again for providing this plugin.  It's really awesome!
